### ISSUE TITLE
Access level to WyChoong\FilamentFortify\Pages\Concerns\HasActionButtons::getCachedAction() must be public (as in class Filament\Pages\Page)

### ISSUE THREAD

**Issue by dtraxx** [wychoong/filament-fortify#11]
at vendor/wychoong/filament-fortify/src/Pages/Concerns/HasActionButtons.php:38
     34▕             })
     35▕             ->toArray();
     36▕     }
     37▕ 
  ➜  38▕     protected function getCachedAction(string $name): ?Action
     39▕     {
     40▕         return $this->getCachedButtons()[$name] ?? parent::getCachedAction($name);
     41▕     }
     42▕ 
Apparently Filament updated this class to public.
When you do composer require or update this will throw an error.

**Comment by wychoong** [comment]
@dtraxx can you submit a pr?

**Comment by dtraxx** [comment]
<img width="1472" alt="Screenshot 2022-07-26 at 18 42 39" src="https://user-images.githubusercontent.com/77774839/181063328-5847ead5-f91a-471a-b02d-dfdd0803f572.png">

**Comment by wychoong** [comment]
@dtraxx  try the new release

**Comment by dtraxx** [comment]
Wychoong/Filament-Fortify,

Thanksfor the quick fix :)

Regards


Steven Vandenbroeck
