### ISSUE TITLE
Can't change auth to username + pasword

### ISSUE THREAD

**Issue by NoahNxT** [wychoong/filament-fortify#17]
For some reason normally you could override the Authentication method by using 
`Fortify::authenticateUsing()`
in the FortifyServiceProvider, but it won't get in it which normally shouldn't be a problem.

Any idea?

My function:
```       
 Fortify::authenticateUsing(function (Request $request) {
            $login = $request->abbreviation;
            if (filter_var($login, FILTER_VALIDATE_EMAIL)) {
                $user = User::where('email', $login)->first();
            } else {
                $user = User::where('abbreviation', $login)->first();
            }

            if ($user && Hash::check($request->password, $user->password)) {
                return $user;
            }
            return null;
        });
```

**Comment by wychoong** [comment]
can't replicate the issue

I have the following code in `FortifyServiceProvider` and logging works fine. please test your code
```php
use Illuminate\Support\Facades\Log;

Fortify::authenticateUsing(function (Request $request) {
    Log::info('test');
});
```

check also your Form fields is having `abbreviation` input field, or check is `abbreviation` is the correct value to get from `$request`
